version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80" # Maps container's port 8080 to host's port 8080
    environment:
      - NODE_ENV=production
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY} # Use the value from the .env file
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network
    env_file:
      - .env # Load environment variables from the .env file

networks:
  app-network:
    driver: bridge
