version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80" # Maps container's port 80 to host's port 8081
    environment:
      - NODE_ENV=production
      - VITE_TMDB_API=${VITE_TMDB_API} # Loads from .env file
    env_file:
      - .env # Load environment variables from the .env file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
