apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-clone
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Amey4044/Netflix_Clone.git
    targetRevision: main
    path: netflix-clone-chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true