apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
      - name: netflix-clone
        image: cypher7/netflix-clone:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: netflix-secrets
              key: VITE_TMDB_API_KEY