apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Change this from NodePort
