apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  type: NodePort
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008